apply plugin: 'com.android.library'

android {
    compileSdkVersion 34
    buildToolsVersion "34.0.0"
    
    if (respondTo("namespace")) {
        namespace "com.github.reveny.zygisk"
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
        
        externalNativeBuild {
            if (file("src/main/cpp/CMakeLists.txt").exists()) {
                cmake {
                    arguments "-DANDROID_STL=c++_shared"
                }
            } else if (file("src/main/jni/Android.mk").exists()) {
                ndkBuild {
                    abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
                }
            }
        }
    }

    externalNativeBuild {
        if (file("src/main/cpp/CMakeLists.txt").exists()) {
            cmake {
                path "src/main/cpp/CMakeLists.txt"
            }
        } else if (file("src/main/jni/Android.mk").exists()) {
            ndkBuild {
                path "src/main/jni/Android.mk"
            }
        }
    }
}
