plugins {
    id 'com.android.library'
}

android {
    namespace 'com.reveny.zygisk'
    compileSdk 34

    defaultConfig {
        minSdk 26
        targetSdk 34

        externalNativeBuild {
            ndkBuild {
                arguments "APP_STL:=c++_static", "APP_PLATFORM:=android-26"
                cppFlags "-std=c++20", "-O3"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        ndkBuild {
            path file('src/main/cpp/Android.mk')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
