plugins {
    id 'com.android.library'
}

android {
    compileSdk 34
    ndkVersion "25.1.8937393"

    defaultConfig {
        minSdk 21
        targetSdk 34

        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
        }

        externalNativeBuild {
            ndkBuild {
                arguments "NDK_APPLICATION_MK:=src/main/cpp/Application.mk"
                cppFlags "-std=c++20"
            }
        }
    }

    externalNativeBuild {
        ndkBuild {
            path "src/main/cpp/Android.mk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
